# CMake generated Testfile for 
# Source directory: /home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test
# Build directory: /home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_berendsen_integrator "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_berendsen_integrator")
set_tests_properties(test_berendsen_integrator PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_bondtable_bond_force "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_bondtable_bond_force")
set_tests_properties(test_bondtable_bond_force PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_constraint_sphere "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_constraint_sphere")
set_tests_properties(test_constraint_sphere PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_dipole_force "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_dipole_force")
set_tests_properties(test_dipole_force PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_enforce2d_updater "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_enforce2d_updater")
set_tests_properties(test_enforce2d_updater PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_external_periodic "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_external_periodic")
set_tests_properties(test_external_periodic PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_fenebond_force "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_fenebond_force")
set_tests_properties(test_fenebond_force PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_fire_energy_minimizer "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_fire_energy_minimizer")
set_tests_properties(test_fire_energy_minimizer PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_force_shifted_lj "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_force_shifted_lj")
set_tests_properties(test_force_shifted_lj PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_gaussian_force "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_gaussian_force")
set_tests_properties(test_gaussian_force PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_gayberne_force "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_gayberne_force")
set_tests_properties(test_gayberne_force PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_cosinesq_angle_force "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_cosinesq_angle_force")
set_tests_properties(test_cosinesq_angle_force PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_harmonic_angle_force "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_harmonic_angle_force")
set_tests_properties(test_harmonic_angle_force PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_harmonic_bond_force "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_harmonic_bond_force")
set_tests_properties(test_harmonic_bond_force PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_harmonic_dihedral_force "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_harmonic_dihedral_force")
set_tests_properties(test_harmonic_dihedral_force PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_harmonic_improper_force "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_harmonic_improper_force")
set_tests_properties(test_harmonic_improper_force PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_lj_force "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_lj_force")
set_tests_properties(test_lj_force PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_mie_force "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_mie_force")
set_tests_properties(test_mie_force PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_morse_force "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_morse_force")
set_tests_properties(test_morse_force PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_MolecularForceCompute "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_MolecularForceCompute")
set_tests_properties(test_MolecularForceCompute PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_neighborlist "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_neighborlist")
set_tests_properties(test_neighborlist PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_opls_dihedral_force "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_opls_dihedral_force")
set_tests_properties(test_opls_dihedral_force PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_pppm_force "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_pppm_force")
set_tests_properties(test_pppm_force PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_slj_force "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_slj_force")
set_tests_properties(test_slj_force PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_table_angle_force "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_table_angle_force")
set_tests_properties(test_table_angle_force PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_table_dihedral_force "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_table_dihedral_force")
set_tests_properties(test_table_dihedral_force PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_table_potential "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_table_potential")
set_tests_properties(test_table_potential PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_temp_rescale_updater "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_temp_rescale_updater")
set_tests_properties(test_temp_rescale_updater PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_walldata "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_walldata")
set_tests_properties(test_walldata PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_yukawa_force "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_yukawa_force")
set_tests_properties(test_yukawa_force PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(test_zero_momentum_updater "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_zero_momentum_updater")
set_tests_properties(test_zero_momentum_updater PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;90;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(mpi-test_communication "/usr/bin/mpiexec" "-n" "8" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_communication")
set_tests_properties(mpi-test_communication PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;102;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
add_test(mpi-test_communicator_grid "/usr/bin/mpiexec" "-n" "8" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/test_communicator_grid")
set_tests_properties(mpi-test_communicator_grid PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;102;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/md/test/CMakeLists.txt;0;")
