# CMake generated Testfile for 
# Source directory: /home/mg/Thesis/hoomd-v2.9.7/hoomd/test
# Build directory: /home/mg/Thesis/hoomd-v2.9.7/hoomd/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_cell_list "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/test_cell_list")
set_tests_properties(test_cell_list PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;77;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;0;")
add_test(test_cell_list_stencil "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/test_cell_list_stencil")
set_tests_properties(test_cell_list_stencil PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;77;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;0;")
add_test(test_gpu_array "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/test_gpu_array")
set_tests_properties(test_gpu_array PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;77;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;0;")
add_test(test_global_array "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/test_global_array")
set_tests_properties(test_global_array PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;77;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;0;")
add_test(test_gpu_polymorph "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/test_gpu_polymorph")
set_tests_properties(test_gpu_polymorph PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;77;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;0;")
add_test(test_gridshift_correct "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/test_gridshift_correct")
set_tests_properties(test_gridshift_correct PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;77;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;0;")
add_test(test_index1d "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/test_index1d")
set_tests_properties(test_index1d PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;77;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;0;")
add_test(test_messenger "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/test_messenger")
set_tests_properties(test_messenger PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;77;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;0;")
add_test(test_particle_group "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/test_particle_group")
set_tests_properties(test_particle_group PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;77;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;0;")
add_test(test_pdata "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/test_pdata")
set_tests_properties(test_pdata PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;77;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;0;")
add_test(test_quat "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/test_quat")
set_tests_properties(test_quat PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;77;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;0;")
add_test(test_rotmat2 "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/test_rotmat2")
set_tests_properties(test_rotmat2 PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;77;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;0;")
add_test(test_rotmat3 "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/test_rotmat3")
set_tests_properties(test_rotmat3 PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;77;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;0;")
add_test(test_shared_signal "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/test_shared_signal")
set_tests_properties(test_shared_signal PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;77;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;0;")
add_test(test_system "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/test_system")
set_tests_properties(test_system PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;77;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;0;")
add_test(test_utils "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/test_utils")
set_tests_properties(test_utils PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;77;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;0;")
add_test(test_vec2 "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/test_vec2")
set_tests_properties(test_vec2 PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;77;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;0;")
add_test(test_vec3 "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/test_vec3")
set_tests_properties(test_vec3 PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;77;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;0;")
add_test(random_numbers_test "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/random_numbers_test")
set_tests_properties(random_numbers_test PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;77;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;0;")
add_test(test_warp_tools "/usr/bin/mpiexec" "-n" "1" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/test_warp_tools")
set_tests_properties(test_warp_tools PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;77;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;0;")
add_test(mpi-test_load_balancer "/usr/bin/mpiexec" "-n" "8" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/test_load_balancer")
set_tests_properties(mpi-test_load_balancer PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;89;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;0;")
add_test(test_warp_tools-synccheck "/usr/bin/mpiexec" "-n" "1" "/opt/cuda/bin/cuda-memcheck" "--error-exitcode" "123" "--tool" "synccheck" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/test_warp_tools")
set_tests_properties(test_warp_tools-synccheck PROPERTIES  _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;109;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/test/CMakeLists.txt;0;")
