# CMake generated Testfile for 
# Source directory: /home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py
# Build directory: /home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(dem-test_basic.py-cpu "/usr/bin/python3" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/test_basic.py" "--mode=cpu")
set_tests_properties(dem-test_basic.py-cpu PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/mg/Thesis/hoomd-v2.9.7:" _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;31;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;64;add_script_test_cpu;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;0;")
add_test(dem-test_basic.py-mpi-cpu "/usr/bin/mpiexec" "-n" "2" "/usr/bin/python3" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/test_basic.py" "--mode=cpu")
set_tests_properties(dem-test_basic.py-mpi-cpu PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/mg/Thesis/hoomd-v2.9.7:" _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;8;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;34;add_script_test_cpu_mpi;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;64;add_script_test_cpu;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;0;")
add_test(dem-test_potentials.py-cpu "/usr/bin/python3" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/test_potentials.py" "--mode=cpu")
set_tests_properties(dem-test_potentials.py-cpu PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/mg/Thesis/hoomd-v2.9.7:" _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;31;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;64;add_script_test_cpu;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;0;")
add_test(dem-test_potentials.py-mpi-cpu "/usr/bin/mpiexec" "-n" "2" "/usr/bin/python3" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/test_potentials.py" "--mode=cpu")
set_tests_properties(dem-test_potentials.py-mpi-cpu PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/mg/Thesis/hoomd-v2.9.7:" _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;8;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;34;add_script_test_cpu_mpi;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;64;add_script_test_cpu;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;0;")
add_test(dem-test_utils.py-cpu "/usr/bin/python3" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/test_utils.py" "--mode=cpu")
set_tests_properties(dem-test_utils.py-cpu PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/mg/Thesis/hoomd-v2.9.7:" _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;31;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;64;add_script_test_cpu;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;0;")
add_test(dem-test_utils.py-mpi-cpu "/usr/bin/mpiexec" "-n" "2" "/usr/bin/python3" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/test_utils.py" "--mode=cpu")
set_tests_properties(dem-test_utils.py-mpi-cpu PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/mg/Thesis/hoomd-v2.9.7:" _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;8;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;34;add_script_test_cpu_mpi;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;64;add_script_test_cpu;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;0;")
add_test(dem-test_dem_shape_spec.py-cpu "/usr/bin/python3" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/test_dem_shape_spec.py" "--mode=cpu")
set_tests_properties(dem-test_dem_shape_spec.py-cpu PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/mg/Thesis/hoomd-v2.9.7:" _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;31;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;64;add_script_test_cpu;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;0;")
add_test(dem-test_dem_shape_spec.py-mpi-cpu "/usr/bin/mpiexec" "-n" "2" "/usr/bin/python3" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/test_dem_shape_spec.py" "--mode=cpu")
set_tests_properties(dem-test_dem_shape_spec.py-mpi-cpu PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/mg/Thesis/hoomd-v2.9.7:" _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;8;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;34;add_script_test_cpu_mpi;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;64;add_script_test_cpu;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;0;")
add_test(dem-test_basic.py-gpu "/usr/bin/python3" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/test_basic.py" "--mode=gpu")
set_tests_properties(dem-test_basic.py-gpu PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/mg/Thesis/hoomd-v2.9.7:" _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;38;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;76;add_script_test_gpu;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;0;")
add_test(dem-test_basic.py-mpi-gpu "/usr/bin/mpiexec" "-n" "2" "/usr/bin/python3" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/test_basic.py" "--mode=gpu" "--gpu_error_checking")
set_tests_properties(dem-test_basic.py-mpi-gpu PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/mg/Thesis/hoomd-v2.9.7:" _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;21;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;41;add_script_test_gpu_mpi;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;76;add_script_test_gpu;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;0;")
add_test(dem-test_potentials.py-gpu "/usr/bin/python3" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/test_potentials.py" "--mode=gpu")
set_tests_properties(dem-test_potentials.py-gpu PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/mg/Thesis/hoomd-v2.9.7:" _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;38;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;76;add_script_test_gpu;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;0;")
add_test(dem-test_potentials.py-mpi-gpu "/usr/bin/mpiexec" "-n" "2" "/usr/bin/python3" "/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/test_potentials.py" "--mode=gpu" "--gpu_error_checking")
set_tests_properties(dem-test_potentials.py-mpi-gpu PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/mg/Thesis/hoomd-v2.9.7:" _BACKTRACE_TRIPLES "/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;21;add_test;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;41;add_script_test_gpu_mpi;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;76;add_script_test_gpu;/home/mg/Thesis/hoomd-v2.9.7/hoomd/dem/test-py/CMakeLists.txt;0;")
